
import java.awt.Color;
import java.awt.print.Paper;
import java.io.FileInputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suneater
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnStartConexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel1.setText("Servidor");

        BtnStartConexion.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        BtnStartConexion.setText("Start Server");
        BtnStartConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartConexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnStartConexion)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(BtnStartConexion)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int BuscarPalabra(ArrayList<String>Words,String palabra)
    {
        int Index=0;
        boolean Search = false;
        for (String Word : Words)
        {
            if(Word.equals(palabra))
            {
               Search = true;
                break;
            }
           Index++;
        }
        if(Search == false )
        {
            Index = -1;
        }
        
        return Index;
    }
    private void BtnStartConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartConexionActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Arrancando server");
        this.BtnStartConexion.setBackground(Color.GREEN);
        dataTR DATOS = new  dataTR();
        
        DatagramSocket SocketUDP = null;
        try
         {
             FileInputStream FILE = new FileInputStream("palabras.txt");
             
             Scanner Lectura = new Scanner(FILE);
             ArrayList<String>WordSpanish = new ArrayList<String>();
             ArrayList<String>WordEnglishh = new ArrayList<String>();
             byte[] buf = new  byte[1024];
             String CadenaArchiivo = "";
             Boolean SeguirLeyendo = true;
            
             /*El ciclo lo que hace es leer el archivo todas la palabaras 
             
             *y dividirlas en dos array uno para ingles y otro para español se termina de leer hasta
             que se encuentra la palabra finxxfin*/ 
             while(SeguirLeyendo)
             {
                 CadenaArchiivo = Lectura.nextLine();
                 String[]LineSplit = CadenaArchiivo.split("xx");
                 
                 if(CadenaArchiivo.equalsIgnoreCase("finxxfin"))
                 {
                     SeguirLeyendo= false;
                 }
                 else
                 {
                     WordSpanish.add(LineSplit[0]);
                     WordEnglishh.add(LineSplit[1]);
                 }
                 
             }
             FILE.close();
             Lectura.close();
             
             /*Iniciamos la conexion y se dispone a enviar y recivir mensajes*/
             SocketUDP = new DatagramSocket(5000);
             DatagramPacket Paqcket = new DatagramPacket(buf,buf.length);
             SocketUDP.receive(Paqcket);
             
             String cadena = new String(Paqcket.getData(),0,Paqcket.getLength());
             
             String[]Cadenas = cadena.split("sep");
             String PalabraTraducida = "";
             int IndexElemento;
             
             
             DATOS.Tipo = Integer.parseInt(Cadenas[0]);
             DATOS.Palabra = Cadenas[1];
             
             
             if(DATOS.Tipo == 1)//ingles a español
             {
                 IndexElemento = BuscarPalabra(WordEnglishh, DATOS.Palabra);
                 if(IndexElemento==-1)
                 {
                     PalabraTraducida = "No se encontro la palabra";
                 }
                 else
                 {
                     PalabraTraducida = WordSpanish.get(IndexElemento);
                     
                 }
                 
             }
             
             else //ESPANÑOL TO ENGLISH
             {
                 IndexElemento = BuscarPalabra(WordSpanish, DATOS.Palabra);
                 if(IndexElemento==-1)
                 {
                     PalabraTraducida = "No se encontro la palabra";
                 }
                 else
                 {
                     PalabraTraducida = WordEnglishh.get(IndexElemento);
                     
                 }
             }
             
             /*Enviando respuesta*/
             
            byte[]Eviar = PalabraTraducida.getBytes();
            DatagramPacket Paketsend = new DatagramPacket(Eviar,Eviar.length,Paqcket.getAddress(),Paqcket.getPort());
            
           SocketUDP.send(Paketsend);
           JOptionPane.showMessageDialog(rootPane, "Se envio el mensaje con exito¡¡");
             
             
             
         }
        catch(IOException io)
        {
            JOptionPane.showMessageDialog(rootPane,"Error posiblemente elarchivo no exista: "+ io.getMessage());
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,"Ocurrio un error en el server: "+e.getMessage());
         }
        finally
        {
            if(SocketUDP!= null)
                SocketUDP.close();
            this.BtnStartConexion.setBackground(Color.RED);
            
        }
    }//GEN-LAST:event_BtnStartConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnStartConexion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
